### ISSUE TITLE
release ngx-slice-kit package on tag push

### ISSUE THREAD

**Issue by scDisorder** [rovergulf-archive/ngx-slice-kit#154]
https://github.com/rovergulf/ngx-slice-kit/blob/main/.github/workflows/npm_package.yml#L6-L8

```yaml
on:
  release:
    types: [created]
```
should be changed to:
```yaml
on:
  push:
    tags: ['*']
```
