### ISSUE TITLE
implement new color palette usage

### ISSUE THREAD

**Issue by scDisorder** [rovergulf-archive/ngx-slice-kit#80]
light theme for example:

```css
body {
    
    // base
    --base-a0: rgba(255, 255, 255, 0);
    --base-a5: rgba(255, 255, 255, 0.05);
    --base-a10: rgba(255, 255, 255, 0.1);
    --base-a15: rgba(255, 255, 255, 0.15);
    --base-a20: rgba(255, 255, 255, 0.2);
    --base-a25: rgba(255, 255, 255, 0.25);
    --base-a30: rgba(255, 255, 255, 0.3);
    --base-a35: rgba(255, 255, 255, 0.35);
    --base-a40: rgba(255, 255, 255, 0.4);
    --base-a45: rgba(255, 255, 255, 0.45);
    --base-a50: rgba(255, 255, 255, 0.5);
    --base-a55: rgba(255, 255, 255, 0.55);
    --base-a60: rgba(255, 255, 255, 0.6);
    --base-a65: rgba(255, 255, 255, 0.65);
    --base-a70: rgba(255, 255, 255, 0.7);
    --base-a75: rgba(255, 255, 255, 0.75);
    --base-a80: rgba(255, 255, 255, 0.8);
    --base-a85: rgba(255, 255, 255, 0.85);
    --base-a90: rgba(255, 255, 255, 0.9);
    --base-a95: rgba(255, 255, 255, 0.95);
    --base-a100: rgba(255, 255, 255, 1);
    
    // background
    --background-a0: rgba(26, 26, 26, 0);
    --background-a5: rgba(26, 26, 26, 0.05);
    --background-a10: rgba(26, 26, 26, 0.1);
    --background-a15: rgba(26, 26, 26, 0.15);
    --background-a20: rgba(26, 26, 26, 0.2);
    --background-a25: rgba(26, 26, 26, 0.25);
    --background-a30: rgba(26, 26, 26, 0.3);
    --background-a35: rgba(26, 26, 26, 0.35);
    --background-a40: rgba(26, 26, 26, 0.4);
    --background-a45: rgba(26, 26, 26, 0.45);
    --background-a50: rgba(26, 26, 26, 0.5);
    --background-a55: rgba(26, 26, 26, 0.55);
    --background-a60: rgba(26, 26, 26, 0.6);
    --background-a65: rgba(26, 26, 26, 0.65);
    --background-a70: rgba(26, 26, 26, 0.7);
    --background-a75: rgba(26, 26, 26, 0.75);
    --background-a80: rgba(26, 26, 26, 0.8);
    --background-a85: rgba(26, 26, 26, 0.85);
    --background-a90: rgba(26, 26, 26, 0.9);
    --background-a95: rgba(26, 26, 26, 0.95);
    --background-a100: rgba(26, 26, 26, 1);
    
    // regular
    --regular-a0: rgba(66, 66, 66, 0);
    --regular-a5: rgba(66, 66, 66, 0.05);
    --regular-a10: rgba(66, 66, 66, 0.1);
    --regular-a15: rgba(66, 66, 66, 0.15);
    --regular-a20: rgba(66, 66, 66, 0.2);
    --regular-a25: rgba(66, 66, 66, 0.25);
    --regular-a30: rgba(66, 66, 66, 0.3);
    --regular-a35: rgba(66, 66, 66, 0.35);
    --regular-a40: rgba(66, 66, 66, 0.4);
    --regular-a45: rgba(66, 66, 66, 0.45);
    --regular-a50: rgba(66, 66, 66, 0.5);
    --regular-a55: rgba(66, 66, 66, 0.55);
    --regular-a60: rgba(66, 66, 66, 0.6);
    --regular-a65: rgba(66, 66, 66, 0.65);
    --regular-a70: rgba(66, 66, 66, 0.7);
    --regular-a75: rgba(66, 66, 66, 0.75);
    --regular-a80: rgba(66, 66, 66, 0.8);
    --regular-a85: rgba(66, 66, 66, 0.85);
    --regular-a90: rgba(66, 66, 66, 0.9);
    --regular-a95: rgba(66, 66, 66, 0.95);
    --regular-a100: rgba(66, 66, 66, 1);
    --regular-rgb: rgba(66, 66, 66, 0.75);
    --regular-deep: rgba(66, 66, 66, 1);
    --regular-hover: rgba(66, 66, 66, 0.9);
    --regular-active: rgba(66, 66, 66, 0.6);
    --regular-disabled: rgba(66, 66, 66, 0.45);
    --regular-smooth: rgba(66, 66, 66, 0.1);
    
    // primary
    --primary-a0: rgba(0, 85, 255, 0);
    --primary-a5: rgba(0, 85, 255, 0.05);
    --primary-a10: rgba(0, 85, 255, 0.1);
    --primary-a15: rgba(0, 85, 255, 0.15);
    --primary-a20: rgba(0, 85, 255, 0.2);
    --primary-a25: rgba(0, 85, 255, 0.25);
    --primary-a30: rgba(0, 85, 255, 0.3);
    --primary-a35: rgba(0, 85, 255, 0.35);
    --primary-a40: rgba(0, 85, 255, 0.4);
    --primary-a45: rgba(0, 85, 255, 0.45);
    --primary-a50: rgba(0, 85, 255, 0.5);
    --primary-a55: rgba(0, 85, 255, 0.55);
    --primary-a60: rgba(0, 85, 255, 0.6);
    --primary-a65: rgba(0, 85, 255, 0.65);
    --primary-a70: rgba(0, 85, 255, 0.7);
    --primary-a75: rgba(0, 85, 255, 0.75);
    --primary-a80: rgba(0, 85, 255, 0.8);
    --primary-a85: rgba(0, 85, 255, 0.85);
    --primary-a90: rgba(0, 85, 255, 0.9);
    --primary-a95: rgba(0, 85, 255, 0.95);
    --primary-a100: rgba(0, 85, 255, 1);
    --primary-rgb: rgba(0, 85, 255, 0.75);
    --primary-rgb-text: rgba(255, 255, 255, 0.75);
    --primary-deep: rgba(0, 85, 255, 1);
    --primary-deep-text: rgba(255, 255, 255, 1);
    --primary-hover: rgba(0, 85, 255, 0.9);
    --primary-hover-text: rgba(255, 255, 255, 0.9);
    --primary-active: rgba(0, 85, 255, 0.6);
    --primary-active-text: rgba(255, 255, 255, 0.6);
    --primary-disabled: rgba(0, 85, 255, 0.45);
    --primary-disabled-text: rgba(255, 255, 255, 0.45);
    --primary-smooth: rgba(0, 85, 255, 0.1);
    --primary-smooth-text: rgba(255, 255, 255, 0.1);
    
    // success
    --success-a0: rgba(39, 174, 96, 0);
    --success-a5: rgba(39, 174, 96, 0.05);
    --success-a10: rgba(39, 174, 96, 0.1);
    --success-a15: rgba(39, 174, 96, 0.15);
    --success-a20: rgba(39, 174, 96, 0.2);
    --success-a25: rgba(39, 174, 96, 0.25);
    --success-a30: rgba(39, 174, 96, 0.3);
    --success-a35: rgba(39, 174, 96, 0.35);
    --success-a40: rgba(39, 174, 96, 0.4);
    --success-a45: rgba(39, 174, 96, 0.45);
    --success-a50: rgba(39, 174, 96, 0.5);
    --success-a55: rgba(39, 174, 96, 0.55);
    --success-a60: rgba(39, 174, 96, 0.6);
    --success-a65: rgba(39, 174, 96, 0.65);
    --success-a70: rgba(39, 174, 96, 0.7);
    --success-a75: rgba(39, 174, 96, 0.75);
    --success-a80: rgba(39, 174, 96, 0.8);
    --success-a85: rgba(39, 174, 96, 0.85);
    --success-a90: rgba(39, 174, 96, 0.9);
    --success-a95: rgba(39, 174, 96, 0.95);
    --success-a100: rgba(39, 174, 96, 1);
    --success-rgb: rgba(39, 174, 96, 0.75);
    --success-rgb-text: rgba(255, 255, 255, 0.75);
    --success-deep: rgba(39, 174, 96, 1);
    --success-deep-text: rgba(255, 255, 255, 1);
    --success-hover: rgba(39, 174, 96, 0.9);
    --success-hover-text: rgba(255, 255, 255, 0.9);
    --success-active: rgba(39, 174, 96, 0.6);
    --success-active-text: rgba(255, 255, 255, 0.6);
    --success-disabled: rgba(39, 174, 96, 0.45);
    --success-disabled-text: rgba(255, 255, 255, 0.45);
    --success-smooth: rgba(39, 174, 96, 0.1);
    --success-smooth-text: rgba(255, 255, 255, 0.1);
    
    // accent
    --accent-a0: rgba(241, 201, 79, 0);
    --accent-a5: rgba(241, 201, 79, 0.05);
    --accent-a10: rgba(241, 201, 79, 0.1);
    --accent-a15: rgba(241, 201, 79, 0.15);
    --accent-a20: rgba(241, 201, 79, 0.2);
    --accent-a25: rgba(241, 201, 79, 0.25);
    --accent-a30: rgba(241, 201, 79, 0.3);
    --accent-a35: rgba(241, 201, 79, 0.35);
    --accent-a40: rgba(241, 201, 79, 0.4);
    --accent-a45: rgba(241, 201, 79, 0.45);
    --accent-a50: rgba(241, 201, 79, 0.5);
    --accent-a55: rgba(241, 201, 79, 0.55);
    --accent-a60: rgba(241, 201, 79, 0.6);
    --accent-a65: rgba(241, 201, 79, 0.65);
    --accent-a70: rgba(241, 201, 79, 0.7);
    --accent-a75: rgba(241, 201, 79, 0.75);
    --accent-a80: rgba(241, 201, 79, 0.8);
    --accent-a85: rgba(241, 201, 79, 0.85);
    --accent-a90: rgba(241, 201, 79, 0.9);
    --accent-a95: rgba(241, 201, 79, 0.95);
    --accent-a100: rgba(241, 201, 79, 1);
    --accent-rgb: rgba(241, 201, 79, 0.75);
    --accent-rgb-text: rgba(255, 255, 255, 0.75);
    --accent-deep: rgba(241, 201, 79, 1);
    --accent-deep-text: rgba(255, 255, 255, 1);
    --accent-hover: rgba(241, 201, 79, 0.9);
    --accent-hover-text: rgba(255, 255, 255, 0.9);
    --accent-active: rgba(241, 201, 79, 0.6);
    --accent-active-text: rgba(255, 255, 255, 0.6);
    --accent-disabled: rgba(241, 201, 79, 0.45);
    --accent-disabled-text: rgba(255, 255, 255, 0.45);
    --accent-smooth: rgba(241, 201, 79, 0.1);
    --accent-smooth-text: rgba(255, 255, 255, 0.1);
    
    // warn
    --warn-a0: rgba(211, 50, 39, 0);
    --warn-a5: rgba(211, 50, 39, 0.05);
    --warn-a10: rgba(211, 50, 39, 0.1);
    --warn-a15: rgba(211, 50, 39, 0.15);
    --warn-a20: rgba(211, 50, 39, 0.2);
    --warn-a25: rgba(211, 50, 39, 0.25);
    --warn-a30: rgba(211, 50, 39, 0.3);
    --warn-a35: rgba(211, 50, 39, 0.35);
    --warn-a40: rgba(211, 50, 39, 0.4);
    --warn-a45: rgba(211, 50, 39, 0.45);
    --warn-a50: rgba(211, 50, 39, 0.5);
    --warn-a55: rgba(211, 50, 39, 0.55);
    --warn-a60: rgba(211, 50, 39, 0.6);
    --warn-a65: rgba(211, 50, 39, 0.65);
    --warn-a70: rgba(211, 50, 39, 0.7);
    --warn-a75: rgba(211, 50, 39, 0.75);
    --warn-a80: rgba(211, 50, 39, 0.8);
    --warn-a85: rgba(211, 50, 39, 0.85);
    --warn-a90: rgba(211, 50, 39, 0.9);
    --warn-a95: rgba(211, 50, 39, 0.95);
    --warn-a100: rgba(211, 50, 39, 1);
    --warn-rgb: rgba(211, 50, 39, 0.75);
    --warn-rgb-text: rgba(255, 255, 255, 0.75);
    --warn-deep: rgba(211, 50, 39, 1);
    --warn-deep-text: rgba(255, 255, 255, 1);
    --warn-hover: rgba(211, 50, 39, 0.9);
    --warn-hover-text: rgba(255, 255, 255, 0.9);
    --warn-active: rgba(211, 50, 39, 0.6);
    --warn-active-text: rgba(255, 255, 255, 0.6);
    --warn-disabled: rgba(211, 50, 39, 0.45);
    --warn-disabled-text: rgba(255, 255, 255, 0.45);
    --warn-smooth: rgba(211, 50, 39, 0.1);
    --warn-smooth-text: rgba(255, 255, 255, 0.1);
}
```

**Comment by scDisorder** [comment]
there is also a bunch of classes generated with `core/styles/core.scss`

```css
/**
 * slice-kit colors
 */
body {
  color: var(--base-a100);
  background-color: var(--background-a100);
}
body .sdk-regular-text {
  color: var(--regular-a80);
}
body .sdk-regular-text:hover {
  color: var(--regular-a100);
}
body .sdk-regular-background {
  background-color: var(--regular-a80);
  color: var(--base-a80);
}
body .sdk-regular-background:hover {
  background-color: var(--regular-a100);
  color: var(--base-a100);
}
body .sdk-regular-background.disabled, body .sdk-regular-background[disabled] {
  pointer-events: none;
  cursor: default;
  opacity: 0.5;
}
body .sdk-regular-border {
  border-color: var(--regular-a80);
}
body .sdk-regular-border:hover {
  border-color: var(--regular-a100);
}
body .sdk-primary-text {
  color: var(--primary-a80);
}
body .sdk-primary-text:hover {
  color: var(--primary-a100);
}
body .sdk-primary-background {
  background-color: var(--primary-a80);
  color: var(--base-a80);
}
body .sdk-primary-background:hover {
  background-color: var(--primary-a100);
  color: var(--base-a100);
}
body .sdk-primary-background.disabled, body .sdk-primary-background[disabled] {
  pointer-events: none;
  cursor: default;
  opacity: 0.5;
}
body .sdk-primary-border {
  border-color: var(--primary-a80);
}
body .sdk-primary-border:hover {
  border-color: var(--primary-a100);
}
body .sdk-success-text {
  color: var(--success-a80);
}
body .sdk-success-text:hover {
  color: var(--success-a100);
}
body .sdk-success-background {
  background-color: var(--success-a80);
  color: var(--base-a80);
}
body .sdk-success-background:hover {
  background-color: var(--success-a100);
  color: var(--base-a100);
}
body .sdk-success-background.disabled, body .sdk-success-background[disabled] {
  pointer-events: none;
  cursor: default;
  opacity: 0.5;
}
body .sdk-success-border {
  border-color: var(--success-a80);
}
body .sdk-success-border:hover {
  border-color: var(--success-a100);
}
body .sdk-accent-text {
  color: var(--accent-a80);
}
body .sdk-accent-text:hover {
  color: var(--accent-a100);
}
body .sdk-accent-background {
  background-color: var(--accent-a80);
  color: var(--base-a80);
}
body .sdk-accent-background:hover {
  background-color: var(--accent-a100);
  color: var(--base-a100);
}
body .sdk-accent-background.disabled, body .sdk-accent-background[disabled] {
  pointer-events: none;
  cursor: default;
  opacity: 0.5;
}
body .sdk-accent-border {
  border-color: var(--accent-a80);
}
body .sdk-accent-border:hover {
  border-color: var(--accent-a100);
}
body .sdk-warn-text {
  color: var(--warn-a80);
}
body .sdk-warn-text:hover {
  color: var(--warn-a100);
}
body .sdk-warn-background {
  background-color: var(--warn-a80);
  color: var(--base-a80);
}
body .sdk-warn-background:hover {
  background-color: var(--warn-a100);
  color: var(--base-a100);
}
body .sdk-warn-background.disabled, body .sdk-warn-background[disabled] {
  pointer-events: none;
  cursor: default;
  opacity: 0.5;
}
body .sdk-warn-border {
  border-color: var(--warn-a80);
}
body .sdk-warn-border:hover {
  border-color: var(--warn-a100);
}
```
